#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

PROG=/usr/bin/xray
CONFIG=/etc/xray/config.json

start_service() {
    procd_open_instance
    procd_set_param command $PROG run -c $CONFIG
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger xray
}