#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10
NAME=xray
BIN=/usr/bin/xray
CONF=/etc/xray/config.json

start_service() {
    [ -f "$BIN" ] || { echo "? Xray binary not found"; return 1; }
    [ -f "$CONF" ] || { echo "? Config not found, copying example"; cp /etc/xray/config.json.example $CONF; }

    procd_open_instance "$NAME"
    procd_set_param command "$BIN" run -c "$CONF"
    procd_set_param respawn
    procd_close_instance
}

reload_service() {
    stop
    start
}
