name: Build and Release Xray APK

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  PACKAGE_NAME: xray-core
  OPENWRT_VERSION: 25.12.2
  CACHE_DIR: ~/cache

jobs:
  release:
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            sdk_url: https://downloads.openwrt.org/releases/25.12.2/targets/x86/64/openwrt-sdk-25.12.2-x86-64_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          - arch: aarch64_cortex-a53
            sdk_url: https://downloads.openwrt.org/releases/25.12.2/targets/mediatek/filogic/openwrt-sdk-25.12.2-mediatek-filogic_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          - arch: aarch64_cortex-a72
            sdk_url: https://downloads.openwrt.org/releases/25.12.2/targets/mvebu/cortexa72/openwrt-sdk-25.12.2-mvebu-cortexa72_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          - arch: arm_cortex-a7_neon-vfpv4
            sdk_url: https://downloads.openwrt.org/releases/25.12.2/targets/bcm27xx/bcm2709/openwrt-sdk-25.12.2-bcm27xx-bcm2709_gcc-14.3.0_musl_eabi.Linux-x86_64.tar.zst
          - arch: aarch64_generic
            sdk_url: https://downloads.openwrt.org/releases/25.12.2/targets/rockchip/armv8/openwrt-sdk-25.12.2-rockchip-armv8_gcc-14.3.0_musl.Linux-x86_64.tar.zst

    env:
      CCACHE_DIR: ~/.ccache
      CONFIG_CCACHE: y

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Cache Key
        id: cache_key
        run: echo "::set-output name=timestamp::$(date +%s)"

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.CACHE_DIR }}
            ${{ env.CCACHE_DIR }}
          key: openwrt-${{ matrix.arch }}-${{ env.PACKAGE_NAME }}-${{ steps.cache_key.outputs.timestamp }}
          restore-keys: |
            openwrt-${{ matrix.arch }}-${{ env.PACKAGE_NAME }}-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3 python3-setuptools python3-pip \
            rsync unzip file wget curl zstd p7zip-full

      - name: Create Directories
        run: |
          CACHE_DIR_SDK="$CACHE_DIR/sdk"
          CACHE_DIR_DL="$CACHE_DIR/dl"
          CACHE_DIR_FEEDS="$CACHE_DIR/feeds"
          mkdir -p "$CACHE_DIR_SDK" "$CACHE_DIR_DL" "$CACHE_DIR_FEEDS"
          echo "CACHE_DIR_SDK=$CACHE_DIR_SDK" >> $GITHUB_ENV
          echo "CACHE_DIR_DL=$CACHE_DIR_DL" >> $GITHUB_ENV
          echo "CACHE_DIR_FEEDS=$CACHE_DIR_FEEDS" >> $GITHUB_ENV
          echo "SDK_HOME=$(mktemp -d)" >> $GITHUB_ENV

      - name: Download and Extract SDK
        run: |
          cd "$CACHE_DIR_SDK"
          SDK_FILE=$(basename ${{ matrix.sdk_url }})
          wget -q ${{ matrix.sdk_url }} || { echo "❌ Failed to download SDK"; exit 1; }
          tar --zstd -xf $SDK_FILE --strip-components=1 -C "$SDK_HOME"

      - name: Setup Feeds and Package
        run: |
          cd "$SDK_HOME"
          ./scripts/feeds update -a
          ./scripts/feeds install -a

          # копируем xray-core в feeds/packages/net
          mkdir -p feeds/packages/net
          cp -r $GITHUB_WORKSPACE feeds/packages/net/xray-core

          ./scripts/feeds install xray-core

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Build Package
        run: |
          cd "$SDK_HOME"
          make defconfig
          make package/xray-core/clean V=s
          make package/xray-core/compile V=s

      - name: Collect APK
        run: |
          cd "$SDK_HOME"
          echo "📦 Searching APK..."
          ARCH_SUFFIX=${{ matrix.arch }}
          for f in $(find bin/ -type f -name "openwrt-xray-*.apk"); do
              cp "$f" "$GITHUB_WORKSPACE/$(basename $f .apk)-${ARCH_SUFFIX}.apk"
          done
          ls -lh *.apk || (echo "❌ No APK found" && exit 1)

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: '*.apk'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    name: Notify Release Publish
    runs-on: ubuntu-latest
    env:
      TRIGGER_URL: ${{ secrets.TRIGGER_URL }}
      TRIGGER_TOKEN: ${{ secrets.TRIGGER_TOKEN }}
    needs: release
    steps:
      - name: Notify Jenkins
        run: |
          if [ -z "$TRIGGER_URL" ]; then
            echo "::warning::No trigger url found, skip..."
            exit 0
          fi
          curl -X POST \
            -H "Content-Type: application/json; charset=utf-8" \
            -H "Authorization: Bearer $TRIGGER_TOKEN" \
            -d "{\"event\":\"release\",\"repository\":\"${{ github.repository }}\",\"ref\":\"${{ github.ref }}\"}" \
            "$TRIGGER_URL" || true
